### ISSUE TITLE
Bug tracking for Epoch 1.0.6

### ISSUE THREAD

**Issue by noxsicarius** [noxsicarius/Epoch-Admin-Tools#304]
List any known bugs with the 1.0.6 update below and I will add it to the list if it is verified. Please make sure you are using the TestBranch and not the master. You can find the test branch here: https://github.com/noxsicarius/Epoch-Admin-Tools/tree/TestBranch

- [ ] Temporary vehicles kill you
- [ ] Admin build needs to be rewritten
- [ ] Teleport player to you needs to be tested

**Comment by noxsicarius** [comment]
Looks like I have to modify the scheduler to get teleport to work

**Comment by tux-box** [comment]
Getting kicked off by BattlEye: Script Restriction #8
Snip from scripts log.
08.01.2017 18:16:39: DUDE (DUD-IP) b-DUDE-GUID-d - #8 "6) && (!isNull _ct && !_friend)) then {
(findDisplay 106) closeDisplay 1;
waitUntil {isNull (FindDisplay 106)};
createGearDialog"

**Comment by noxsicarius** [comment]
Try the battleye/scripts in the test branch now.

**Comment by tux-box** [comment]
More battleye kicks. This time for #24. I'm including the whole file this time as I don't know if the other stuff matters to you. 

13.01.2017 15:24:04: DUDE (DUDE-IP) b-DUDE-GUID-d - #49 "5, [["expression", "pselect5 = 'exit';"]], "1", "1"]];
showCommandingMenu "#USER:_pmenu";
};



myfnc_MDarray = {
private ["_lis"
13.01.2017 15:24:11: DUDE (DUDE-IP) b-DUDE-GUID-d - #24 "{
{
if (!isNull _x && !isPlayer _x) then {
_x setDamage 1;
hideObject _x;
} else {
_zombies = _zombies - [_x];
};
} forEach _zom"

**Comment by noxsicarius** [comment]
What restriction is it? I don't know what filter is kicking without the actual kick information: BattlEye: publicvariable restriction #790

**Comment by MichaelSGallagher** [comment]
Need to change a typo in line 56 57 of GodModeVehicle.sql from in test branch.

 vehicle_handleDamage = compile preprocessFileLineNumbers "\z\addons\dayz_code\compile\veh_handleDamage.sqf";
fnc_veh_handleKilled = compile preprocessFileLineNumbers "\z\addons\dayz_code\compile\veh_handleKilled.sqf";

TO:

 vehicle_handleDamage = compile preprocessFileLineNumbers "\z\addons\dayz_code\compile\vehicle_handleDamage.sqf";
fnc_veh_handleKilled = compile preprocessFileLineNumbers "\z\addons\dayz_code\compile\vehicle_handleKilled.sqf";

It will save script not found error popping up in game at Least with Epoch 1.0.5.1 not sure about 1.0.6 yet I think code is the same as this references DayZ code 1.8.8 anyway.

**Comment by noxsicarius** [comment]
Those had to be changed to work with 106. They changed the file and variable names. The test branch is being set up for 106, which will not work with 105 due to a number of changes. There is a 105 release on the release section that works fine.

**Comment by MichaelSGallagher** [comment]
If you look closely, your refering to dayz_code in those lines has
absolutely nothing to do with any calls to Epoch your pulling in Dayz_code
in which 1.8.8 didn't change that reference at all to those damage calls or
the file names. I got your test branch almost compatible with both Epoch
1.0.6 and 1.0.5.1 without much changed to code. I've been also messing
around with it working server side I will commit those changes to my fork
if you want to take a look. Just trying to contribute.

**Comment by noxsicarius** [comment]
If I came off a bit upset ignore it, I've been incredibly drained between my full time job, this, friends, and family. ALL help is useful and improves the community.

The variable for 105 was vehicle_handleDamage and the file name was the same, but according to the list of variable changes the name became fnc_veh_handleDam and the name became veh_handleDam. The new damage handler file [can be found here ](https://github.com/EpochModTeam/DayZ-Epoch/blob/Release_1.0.6/SQF/dayz_code/compile/veh_handleDam.sqf)
The same goes for the other handler. This should not be bridgeable between the two versions since both have different names for both file and variable. 
If I have this wrong let me know and point me to the right files. It wouldn't be the first time.

**Comment by tux-box** [comment]
> noxsicarius commented 3 days ago • edited
What restriction is it? I don't know what filter is kicking without the actual kick information: BattlEye: publicvariable restriction #790 I'm guessing that is in the scripts one. Did you have to do anything extra to get battleye running? For some reason mine is no longer kicking for restrictions so it's kind of hard to check for these.

Sorry, Script restriction.

**Comment by MichaelSGallagher** [comment]
Until they Change the DayZ_Epoch Client files to reflect these changes 
either on a test release It's still going to have the same filename reference. It's as simple as un-pbo the @DayZ_Epoch client file dayz_code.pbo and checking if the file names have changed in the compiles section. I understand with keeping up with changes but that could revert quickly in a testing environment just trying to save you headaches in the future.

**Comment by noxsicarius** [comment]
Are you sure you are looking at the current released 1.0.6 files? I just got home and looked through them and they are named veh_handleDam and veh_handleKilled in the client dayzcode. I have been joining 1.0.6 servers with these files without any problem so they can't be wrong. 

![image](https://cloud.githubusercontent.com/assets/2829971/22086668/ef74e46c-dda7-11e6-8dbd-2120643dea13.png)

**Comment by MichaelSGallagher** [comment]
My bad for Epoch 1.0.6 your correct. I've been looking at the code but your right which prompted me to do some rewrites to my own fork for checking which Epoch version is in use then it can automatically through the script detect this and would then be reverse compatible as for Epoch 1.0.5.1 again sorry I forgot your targeting the test branch for 1.0.6.


Sent from my MetroPCS 4G LTE Android Device
-------- Original message --------From: Ricky Sanders <notifications@github.com> Date: 1/18/17  4:00 PM  (GMT-07:00) To: noxsicarius/Epoch-Admin-Tools <Epoch-Admin-Tools@noreply.github.com> Cc: Michael Gallagher <mikewizcob@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [noxsicarius/Epoch-Admin-Tools] Bug tracking for Epoch 1.0.6
  (#304) 
Are you sure you are looking at the current released 1.0.6 files? I just got home and looked through them and they are named veh_handleDam and veh_handleKilled in the client dayzcode. I have been joining 1.0.6 servers with these files without any problem so they can't be wrong.


—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/noxsicarius/Epoch-Admin-Tools","title":"noxsicarius/Epoch-Admin-Tools","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/noxsicarius/Epoch-Admin-Tools"}},"updates":{"snippets":[{"icon":"PERSON","message":"@noxsicarius in #304: Are you sure you are looking at the current released 1.0.6 files? I just got home and looked through them and they are named veh_handleDam and veh_handleKilled in the client dayzcode. I have been joining 1.0.6 servers with these files without any problem so they can't be wrong. \r\n\r\n![image](https://cloud.githubusercontent.com/assets/2829971/22086668/ef74e46c-dda7-11e6-8dbd-2120643dea13.png)"}],"action":{"name":"View Issue","url":"https://github.com/noxsicarius/Epoch-Admin-Tools/issues/304#issuecomment-273629478"}}}

**Comment by noxsicarius** [comment]
The test branch was working for 105 already, the only new changes are to make it work with 106. I will probably mark a release from the test branch on the last 105 commit and then mark a different one for 106 after it is finished. The main reason for separate version releases is that versioning within code can become messy after a few releases and would eventually need to be refactored. I understand your use for that (if you run servers in both versions it's definitely much better that way), but from a release standpoint it's messier. I used a similar system to detect snap pro and infistar. I still use the infistar detection for the safezones, but I don't use it for snap pro now that it is part of 106. Getting this thing server only would be pretty great and I honestly haven't worked on that much. Let me know if you get that working and we can merge you in. I played with a gui system for a while, but I honestly don't have the time for that now and building a gui for this is uncommonly time consuming. That probably won't happy anymore. 90% of my replies on these things actually come from me while taking a short brake at work now. The things we do for good money.

**Comment by MichaelSGallagher** [comment]
I noticed since the master release quite awhile ago there were many issues among them GodMode ect. I recently realized that all that was fixed in the test branch as well but one thing I noticed, not really to do with your tools or even mods in general, is that Arma2OA and Arma2 have some kinda glitch sometimes from the client side of things after already downloading a client pbo from the server. So whenever I'm testing, I always delete my client side pbo and have it re-download it when I join the server. There seems to be a bug with it overwriting sometimes. This could also be a windows issue or such. Anyway, I'm going to be working this weekend on my Fork of your project and server-side install and GUI system. Shouldn't take much coding but I'm up for it if it dose, yes it's a bit tedious but well worth the effort for an already great mod and community here.

**Comment by noxsicarius** [comment]
Yes, arma code is incredibly glitchy and there are some pretty stupid circumstances that arise from them. I spent two hours trying to fix a file one time that looked perfect. I deleted all the comments so I could better see the code and reran it to just get a better baseline for what is wrong. The file ran perfectly. I added // TEST to the top of the file and it stopped working again. Having a single comment in that file (and only that file) broke the mod until you deleted the client data. This is definitely the most exhausting language I have had to deal with and I've worked with Lisp and Prolog. BTW, here's one of the reasons I've been too busy to work on this: https://www.youtube.com/watch?v=ZCeOaNCHnm0

**Comment by MichaelSGallagher** [comment]
Wow that video is some awesome stuff! Oh ya let me be the back end coder on those projects, not! I see your headache one thing I would suggest though is putting a cotton ball on the tablet device that takes the voice commands in the field this way you have a bit more noise cancelling on the mic and may get better command responses from the app. But great work your doing there in real life noxsicarius!

**Comment by Jejeleponey** [comment]
Hello guys,

I use this script on my server on epoch 1.0.6.1, it work fine but there are a list of bugs i've found:
- Weather menu (fog, rain, night/day) no longer affect all players, only affect the admin
- Epoch unlock menu: When you unlock a safe, it remove all items inside (!!!)
- Admin heal function: Depending of the radius, it always heal all players connected
- Player ESP: When players are in a group, can only see the group owner on the map
- Enhanced ESP option menu: F5 now used by Group Management, tried to set Key Binding to F7 in config but doesnt work (maybe my fault)
- Have a huge FPS drop when I use Enhanced ESP (not on 1.0.5.1)

Thanks for your work !
